on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: |
          mkdir book/
          touch book/.nojekyll
      - uses: XAMPPRocky/deploy-mdbook@v1
        env:
          GITHUB_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
        if: github.ref == 'refs/heads/master'
